sudo: false
language: php
php: 5.5
before_script: composer install --dev
script:
  - ./vendor/bin/phpunit --tap --bootstrap ./vendor/autoload.php -v --coverage-clover build/logs/clover.xml test
  - sonar-scanner
after_script:
  - ./bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

addons:
  sonarcloud:
    organization: "szaboferee-github" # the key of the org you chose at step #3
